### ISSUE TITLE
[Feature Request] Download object method

### ISSUE THREAD

**Issue by holinov** [Neurodyne/zio-aws-s3#5]
Now it's impossible to download object from bucket.
To do this i need to call
`s3.getObject(GetObjectRequest.builder().bucket(bucket).key(key).build(),
        ResponseTransformer.toFile(Paths.get("multiPartKey")));` but there is no way to pass `ResponseTransformer` то `def getObject(buck: String, key: String, file: String)(implicit s3: S3AsyncClient)`

**Comment by holinov** [comment]
Created https://github.com/Neurodyne/zio-aws-s3/pull/6

**Comment by tampler** [comment]
Merged in #6
